# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: petstore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epetstore.proto\x12\x08petstore\x1a\x1bgoogle/protobuf/empty.proto\"\xa9\x02\n\x03Pet\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x15.petstore.Pet.PetTypeR\x04type\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n\x03\x61ge\x18\x04 \x01(\x03R\x03\x61ge\x12=\n\nattributes\x18\x05 \x03(\x0b\x32\x1d.petstore.Pet.AttributesEntryR\nattributes\x1a=\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"C\n\x07PetType\x12\x14\n\x10PET_TYPE_UNKNOWN\x10\x00\x12\x10\n\x0cPET_TYPE_DOG\x10\x01\x12\x10\n\x0cPET_TYPE_CAT\x10\x02\x32p\n\x0fPetStoreService\x12*\n\x08Register\x12\r.petstore.Pet\x1a\r.petstore.Pet\"\x00\x12\x31\n\x04List\x12\x16.google.protobuf.Empty\x1a\r.petstore.Pet\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'petstore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PET_ATTRIBUTESENTRY._options = None
  _PET_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _globals['_PET']._serialized_start=58
  _globals['_PET']._serialized_end=355
  _globals['_PET_ATTRIBUTESENTRY']._serialized_start=225
  _globals['_PET_ATTRIBUTESENTRY']._serialized_end=286
  _globals['_PET_PETTYPE']._serialized_start=288
  _globals['_PET_PETTYPE']._serialized_end=355
  _globals['_PETSTORESERVICE']._serialized_start=357
  _globals['_PETSTORESERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
